version: "3.8"

services:

  deepstack-ui:
    image: robmarkcole/deepstack-ui
    ports:
      - "8501:8501"
    environment:
      - DEEPSTACK_IP=deepstack
      - DEEPSTACK_PORT=5000
      - DEEPSTACK_TIMEOUT=20
      # API-KEY=******
      # DEEPSTACK_CUSTOM_MODEL=xxx
    depends_on:
      - deepstack
    restart: unless-stopped

  deepstack:
    image: deepquestai/deepstack
    ports:
      - "5000:5000"
    volumes:
      - ./data/datastore:/datastore
      - ./data/modelstore:/modelstore/detection
    environment:
      - MODE=Medium
      - VISION-DETECTION=True
      - VISION-FACE=True
      - VISION-SCENE=True
      # DEEPSTACK_API_KEY=******
    restart: unless-stopped
