version: "3.8"
services:
  nfs:
    image: easypi/nfs
    volumes:
      - ./data:/data
    environment:
      - EXPORT_ID=0
      - EXPORT_PATH=/data
      - PSEUDO_PATH=/
    privileged: true
    network_mode: host
    restart: unless-stopped
