version: "3.8"
services:
  hass:
    container_name: hass
    image: homeassistant/home-assistant:stable
    volumes:
      - ./data:/config
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
    network_mode: host
    privileged: true
    restart: unless-stopped
