version: "3.8"
services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - ./data/data:/data
      - ./data/datalog:/datalog
      - ./data/logs:/logs
    environment:
      - ZOO_LOG4J_PROP=INFO,ROLLINGFILE
      - ZOO_STANDALONE_ENABLED=true
    restart: unless-stopped
