version: '3.8'

services:

  hub:
    image: selenium/hub:4
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "127.0.0.1", "--port", "4444"]
      interval: 15s
      timeout: 30s
      retries: 5
    restart: unless-stopped
