version: "3.8"

services:

  opencart:
    image: jeffrey897/opencart
    ports:
      - "8000:80"
    volumes:
      - /var/www
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=QWE123qwe
      - MYSQL_DATABASE=opencart
    restart: unless-stopped
