version: "3.8"
services:
  minio:
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./conf:/root/.minio
    environment:
      - MINIO_ROOT_USER=XXXXXXXXXXXXXXXXXXXX
      - MINIO_ROOT_PASSWORD=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
    restart: unless-stopped
