version: "3.8"

services:

  oss:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: gateway oss https://oss-cn-beijing.aliyuncs.com
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=oss_access_key
      - MINIO_SECRET_KEY=oss_secret_key
    restart: unless-stopped

  s3:
    image: minio/minio
    command: gateway s3
    ports:
      - "9001:9000"
    environment:
      - MINIO_ROOT_USER=aws_s3_access_key
      - MINIO_ROOT_PASSWORD=aws_s3_secret_key
    restart: unless-stopped

  nas:
    image: minio/minio
    command: gateway nas /data
    ports:
      - "9002:9000"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=nas_access_key
      - MINIO_ROOT_PASSWORD=nas_secret_key
    restart: unless-stopped
