version: "3.8"
services:
  semaphore:
    image: easypi/semaphore-arm64
    command: ["semaphore", "server", "--config", "/etc/semaphore/config.json"]
    ports:
      - "3000:3000"
    volumes:
      - ./data/etc:/etc/semaphore
      - ./data/var:/var/lib/semaphore
    tmpfs:
      - /tmp
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    working_dir: /etc/semaphore
    restart: unless-stopped
